import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';

export const THEME = {
  light: {
    background: '#EEF0F3',
    foreground: '#181B21',
    card: '#FFFFFF',
    cardForeground: '#181B21',
    popover: '#FFFFFF',
    popoverForeground: '#181B21',
    primary: '#834965',
    primaryForeground: '#FFFFFF',
    secondary: '#61904C',
    secondaryForeground: '#FFFFFF',
    muted: '#E8EAEE',
    mutedForeground: '#5A6072',
    accent: '#ECDCE3',
    accentForeground: '#53293E',
    destructive: '#B8332E',
    border: '#C9CFD8',
    input: '#C9CFD8',
    ring: '#A77489',
    radius: '0.625rem',
    chart1: '#834965',
    chart2: '#61904C',
    chart3: '#A37598',
    chart4: '#49739A',
    chart5: '#3FBFA9',
  },
  dark: {
    background: '#14171C',
    foreground: '#E6E9EF',
    card: '#1C2027',
    cardForeground: '#E6E9EF',
    popover: '#232831',
    popoverForeground: '#E6E9EF',
    primary: '#AE7891',
    primaryForeground: '#151012',
    secondary: '#79AC70',
    secondaryForeground: '#0B140A',
    muted: '#232831',
    mutedForeground: '#9097A6',
    accent: '#39252F',
    accentForeground: '#D6B3C6',
    destructive: '#D4524C',
    border: '#353C48',
    input: '#353C48',
    ring: '#C096AD',
    radius: '0.625rem',
    chart1: '#AE7891',
    chart2: '#79AC70',
    chart3: '#C096AD',
    chart4: '#6992B9',
    chart5: '#65D3C1',
  },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
