import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';

export const THEME = {
  light: {
    background: '#F2EFEA',
    foreground: '#41393C',
    card: '#F2EFEA',
    cardForeground: '#41393C',
    popover: '#F2EFEA',
    popoverForeground: '#41393C',
    primary: '#82B090',
    primaryForeground: '#F2EFEA',
    secondary: '#D0E4D7',
    secondaryForeground: '#41393C',
    muted: '#E4E0DA',
    mutedForeground: '#7A6E71',
    accent: '#82B090',
    accentForeground: '#F2EFEA',
    destructive: 'hsl(0 84.2% 60.2%)',
    border: '#D5D0CA',
    input: '#D5D0CA',
    ring: '#82B090',
    radius: '0.625rem',
    chart1: '#82B090',
    chart2: '#41393C',
    chart3: '#F2EFEA',
    chart4: '#A8C9B2',
    chart5: '#5E7D66',
  },
  dark: {
    background: '#41393C',
    foreground: '#F2EFEA',
    card: '#4E4449',
    cardForeground: '#F2EFEA',
    popover: '#4E4449',
    popoverForeground: '#F2EFEA',
    primary: '#82B090',
    primaryForeground: '#F2EFEA',
    secondary: '#5E4F53',
    secondaryForeground: '#F2EFEA',
    muted: '#5E4F53',
    mutedForeground: '#B8AFA5',
    accent: '#82B090',
    accentForeground: '#F2EFEA',
    destructive: 'hsl(0 70.9% 59.4%)',
    border: '#5E4F53',
    input: '#5E4F53',
    ring: '#82B090',
    radius: '0.625rem',
    chart1: '#82B090',
    chart2: '#F2EFEA',
    chart3: '#41393C',
    chart4: '#A8C9B2',
    chart5: '#5E7D66',
  },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
